# AWS Credentials
AWS_ACCESS_KEY_ID = "AKIAQKKPJHKHBOZP5M7U"
AWS_SECRET_ACCESS_KEY = "7ZVyS/znyE+M5Ig9K6RUe6NYnxv9lIODEzNI6DNr"

# Other secrets can be added here
# For example:
# DATABASE_URL = "your_database_url"
# API_KEY = "your_api_key" 